### ISSUE TITLE
Edge Hub Dev stops functioning after processing only a few messages

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgehubdev#100]
I've encountered an issue where edge hub dev stops processing messages after only a few +200K sized messages. It appears to be related to module re-authentication.  

I have deleted the original edge device in the portal, and recreated a new device and the problem persists. Also tried both AMQP and MQTT protocols. Error message appears to perhaps indicate an auth failure from the edge sim to IoT Hub. 

See log stack below: 

```
[2018-10-30 04:45:35 : Starting Edge Hub
[10/30/2018 04:45:36.007 AM] Edge Hub Main()
2018-10-30 04:45:39.012 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-10-30 04:45:39.124 +00:00 [INF] - Created device scope identities cache
2018-10-30 04:45:39.145 +00:00 [INF] - Starting Edge Hub
2018-10-30 04:45:39.147 +00:00 [INF] - Version - 1.0.3.17521421 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)
2018-10-30 04:45:39.148 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-10-30 04:45:39.148 +00:00 [INF] - Installing intermediate certificates.
2018-10-30 04:45:39.226 +00:00 [INF] - Starting refresh of device scope identities cache
2018-10-30 04:45:39.329 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-10-30 04:45:39.336 +00:00 [INF] - Created new message store
2018-10-30 04:45:39.770 +00:00 [INF] - Initializing configuration
2018-10-30 04:45:40.512 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
2018-10-30 04:45:40.774 +00:00 [INF] - Set the following 2 route(s) in edge hub
2018-10-30 04:45:40.777 +00:00 [INF] - r1: FROM /messages/modules/ReaderModule/outputs/output1 INTO BrokeredEndpoint("/modules/MlModule/inputs/amlInput")
2018-10-30 04:45:40.777 +00:00 [INF] - r2: FROM /messages/modules/MlModule/outputs/amlOutput INTO BrokeredEndpoint("/modules/WebAppModule/inputs/input1")
2018-10-30 04:45:40.779 +00:00 [INF] - Updated message store TTL to -1 seconds
2018-10-30 04:45:40.779 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-10-30 04:45:40.781 +00:00 [INF] - Initialized edge hub configuration
2018-10-30 04:45:40.835 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2018-10-30 04:45:41.146 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2018-10-30 04:45:41.164 +00:00 [INF] - Starting MQTT head
2018-10-30 04:45:41.360 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-10-30 04:45:41.439 +00:00 [INF] - Starting AMQP head
2018-10-30 04:45:41.467 +00:00 [INF] - Started MQTT head
2018-10-30 04:45:41.610 +00:00 [INF] - Started AMQP head
2018-10-30 04:45:41.615 +00:00 [INF] - Starting HTTP head
2018-10-30 04:45:41.747 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-10-30 04:45:41.784 +00:00 [INF] - Creating key {7ee08d8b-c4db-48bc-8422-9f344fc958aa} with creation date 2018-10-30 04:45:41Z, activation date 2018-10-30 04:45:41Z, and expiration date 2019-01-28 04:45:41Z.
2018-10-30 04:45:41.800 +00:00 [WRN] - No XML encryptor configured. Key {7ee08d8b-c4db-48bc-8422-9f344fc958aa} may be persisted to storage in unencrypted form.
2018-10-30 04:45:41.805 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-7ee08d8b-c4db-48bc-8422-9f344fc958aa.xml"'.
2018-10-30 04:45:42.338 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-10-30 04:45:42.396 +00:00 [INF] - Started HTTP head
2018-10-30 04:45:43.091 +00:00 [INF] - New token received on the Cbs link
2018-10-30 04:45:44.278 +00:00 [WRN] - Error while refreshing the service identity for container/ReaderModule
Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiException: Message: Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized, Content: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:3032dda4197c48129087d94620f631a1-G:3-TimeStamp:10/30/2018 04:45:44"}
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 115
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 85
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs:line 77
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 140
2018-10-30 04:45:44.368 +00:00 [INF] - Attempting to connect to IoT Hub for client container/ReaderModule via AMQP...
2018-10-30 04:45:44.398 +00:00 [INF] - Created cloud proxy for client container/ReaderModule via AMQP, with client operation timeout 20000.
2018-10-30 04:45:44.406 +00:00 [INF] - Initialized cloud proxy 4e4900cb-86d9-4c24-b12c-dbda0ae5f694 for container/ReaderModule
2018-10-30 04:45:44.408 +00:00 [INF] - Created cloud connection for client container/ReaderModule
2018-10-30 04:45:44.410 +00:00 [INF] - New cloud connection created for device container/ReaderModule
2018-10-30 04:45:44.891 +00:00 [INF] - New token received on the Cbs link
2018-10-30 04:45:45.059 +00:00 [INF] - New token requested by client container/ReaderModule, but using existing token as it is usable.
2018-10-30 04:45:45.345 +00:00 [WRN] - Error while refreshing the service identity for container/WebAppModule
Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiException: Message: Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized, Content: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:f1d173c145104b64a8dd400f121ed1c4-G:2-TimeStamp:10/30/2018 04:45:45"}
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 115
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 85
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs:line 77
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 140
2018-10-30 04:45:45.348 +00:00 [INF] - Attempting to connect to IoT Hub for client container/WebAppModule via AMQP...
2018-10-30 04:45:45.349 +00:00 [INF] - Created cloud proxy for client container/WebAppModule via AMQP, with client operation timeout 20000.
2018-10-30 04:45:45.349 +00:00 [INF] - Initialized cloud proxy 7befd60f-6ddf-4843-a834-b8dfebffabc5 for container/WebAppModule
2018-10-30 04:45:45.349 +00:00 [INF] - Created cloud connection for client container/WebAppModule
2018-10-30 04:45:45.349 +00:00 [INF] - New cloud connection created for device container/WebAppModule
2018-10-30 04:45:45.352 +00:00 [INF] - New token requested by client container/WebAppModule, but using existing token as it is usable.
2018-10-30 04:45:45.531 +00:00 [INF] - Exiting disconnected state
2018-10-30 04:45:45.534 +00:00 [INF] - Cloud connection for container/ReaderModule is True
2018-10-30 04:45:45.553 +00:00 [INF] - Connection status for container/ReaderModule changed to ConnectionEstablished
2018-10-30 04:45:45.570 +00:00 [INF] - Processing subscriptions for client container/ReaderModule.
2018-10-30 04:45:45.618 +00:00 [INF] - Cloud connection for container/WebAppModule is True
2018-10-30 04:45:45.618 +00:00 [INF] - Connection status for container/WebAppModule changed to ConnectionEstablished
2018-10-30 04:45:45.618 +00:00 [INF] - Processing subscriptions for client container/WebAppModule.
2018-10-30 04:45:45.625 +00:00 [INF] - Entering connected state
2018-10-30 04:45:45.642 +00:00 [INF] - Authenticated container/WebAppModule with IotHub
2018-10-30 04:45:45.655 +00:00 [INF] - Token updated for container/WebAppModule
2018-10-30 04:45:45.775 +00:00 [INF] - Authenticated container/ReaderModule with IotHub
2018-10-30 04:45:45.776 +00:00 [INF] - Token updated for container/ReaderModule
2018-10-30 04:45:46.007 +00:00 [INF] - New device connection for device container/WebAppModule
2018-10-30 04:45:46.013 +00:00 [INF] - Bind device proxy for device container/WebAppModule
2018-10-30 04:45:46.017 +00:00 [INF] - Initialized AMQP connection handler for container/WebAppModule
2018-10-30 04:45:46.025 +00:00 [INF] - New device connection for device container/ReaderModule
2018-10-30 04:45:46.034 +00:00 [INF] - Bind device proxy for device container/ReaderModule
2018-10-30 04:45:46.036 +00:00 [INF] - Initialized AMQP connection handler for container/ReaderModule
2018-10-30 04:45:46.053 +00:00 [INF] - Opened link Events for container/WebAppModule
2018-10-30 04:45:46.065 +00:00 [INF] - Opened link Events for container/ReaderModule
2018-10-30 04:45:46.282 +00:00 [INF] - Processing subscription ModuleMessages for client container/WebAppModule.
2018-10-30 04:45:46.297 +00:00 [INF] - Opened link ModuleMessages for container/WebAppModule
2018-10-30 04:45:52.389 +00:00 [WRN] - Error while refreshing the service identity for container/MlModule
Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiException: Message: Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized, Content: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:1e322d33999546debe58792b72501053-G:3-TimeStamp:10/30/2018 04:45:52"}
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 115
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 85
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs:line 77
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 140
2018-10-30 04:45:52.391 +00:00 [INF] - Attempting to connect to IoT Hub for client container/MlModule via AMQP...
2018-10-30 04:45:52.391 +00:00 [INF] - Created cloud proxy for client container/MlModule via AMQP, with client operation timeout 20000.
2018-10-30 04:45:52.392 +00:00 [INF] - Initialized cloud proxy e764b06f-5b13-4414-bb7b-ffee489a6acb for container/MlModule
2018-10-30 04:45:52.392 +00:00 [INF] - Created cloud connection for client container/MlModule
2018-10-30 04:45:52.393 +00:00 [INF] - New cloud connection created for device container/MlModule
2018-10-30 04:45:52.393 +00:00 [INF] - New token requested by client container/MlModule, but using existing token as it is usable.
2018-10-30 04:45:52.473 +00:00 [INF] - Cloud connection for container/MlModule is True
2018-10-30 04:45:52.473 +00:00 [INF] - Connection status for container/MlModule changed to ConnectionEstablished
2018-10-30 04:45:52.473 +00:00 [INF] - Processing subscriptions for client container/MlModule.
2018-10-30 04:45:52.473 +00:00 [INF] - Authenticated container/MlModule with IotHub
2018-10-30 04:45:52.479 +00:00 [INF] - Successfully generated identity for clientId container/MlModule and username {host}/container/MlModule/?api-version=2017-11-08-preview&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.17.0-preview-010%20%28.NET%20Core%204.6.0.0%3B%20Linux%204.9.93-linuxkit-aufs%20%231%20SMP%20Wed%20Jun%206%2016%3A55%3A56%20UTC%202018%3B%20X64%29
2018-10-30 04:45:52.487 +00:00 [INF] - ClientAuthenticated, container/MlModule, 3faa42f7
2018-10-30 04:45:52.573 +00:00 [INF] - New device connection for device container/MlModule
2018-10-30 04:45:52.574 +00:00 [INF] - Bind device proxy for device container/MlModule
2018-10-30 04:45:52.577 +00:00 [INF] - Binding message channel for device Id container/MlModule
2018-10-30 04:45:53.445 +00:00 [INF] - Processing subscription TwinResponse for client container/MlModule.
2018-10-30 04:45:53.705 +00:00 [INF] - Set subscriptions from session state for container/MlModule
2018-10-30 04:45:54.905 +00:00 [INF] - Processing subscription TwinResponse for client container/MlModule.
2018-10-30 04:45:54.906 +00:00 [INF] - Processing subscription ModuleMessages for client container/MlModule.
2018-10-30 04:45:54.907 +00:00 [INF] - Set subscriptions from session state for container/MlModule
2018-10-30 04:50:41.168 +00:00 [INF] - Reauthenticating connected clients
```

**Comment by LazarusX** [comment]
Thanks for reporting this issue.

Can you reproduce this issue with the Edge runtime?

**Comment by LazarusX** [comment]
This issue has been fixed in #96, and shipped with 0.5.0 release today. Please `pip install --upgrade iotedgehubdev` and try if the new version works for you.

**Comment by WilliamBerryiii** [comment]
@LazarusX - looks like the fix worked, however a new issue has cropped up in case #106

**Comment by adashen** [comment]
Close as fixed
