### ISSUE TITLE
`iotedgehubdev start` stuck at `Started HTTP head` with Windows container

### ISSUE THREAD

**Issue by LazarusX** [Azure/iotedgehubdev#102]
Version: 0.5.0rc1

```
(venv) PS C:\ iotedgehubdev start -d C:\path\to\deployment_.json -v
Network azure-iot-edge-dev is external, skipping
Pulling edgeHubDev ... done
Creating edgeHubDev ... done
Creating tempSensor ... done
Attaching to edgeHubDev, tempSensor
edgeHubDev    | [10/31/2018 02:27:14.753 AM] Edge Hub Main()
edgeHubDev    | 2018-10-31 10:27:16.699 +08:00 [INF] - Created persistent store at C:\Users\ContainerUser\AppData\Local\Temp\edgeHub
edgeHubDev    | 2018-10-31 10:27:16.768 +08:00 [INF] - Created device scope identities cache
edgeHubDev    | 2018-10-31 10:27:16.782 +08:00 [INF] - Starting Edge Hub
edgeHubDev    | 2018-10-31 10:27:16.784 +08:00 [INF] - Starting refresh of device scope identities cache
edgeHubDev    | 2018-10-31 10:27:16.784 +08:00 [INF] - Version - 1.0.3.17521421 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)
edgeHubDev    | 2018-10-31 10:27:16.785 +08:00 [INF] -
edgeHubDev    |         █████╗ ███████╗██╗   ██╗██████╗ ███████╗
edgeHubDev    |        ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
edgeHubDev    |        ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
edgeHubDev    |        ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
edgeHubDev    |        ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
edgeHubDev    |        ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
edgeHubDev    |
edgeHubDev    |  ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗
███████╗
edgeHubDev    |  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
edgeHubDev    |  ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
edgeHubDev    |  ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
edgeHubDev    |  ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███
████╗
edgeHubDev    |  ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
edgeHubDev    |
edgeHubDev    | 2018-10-31 10:27:16.785 +08:00 [INF] - Installing intermediate certificates.
edgeHubDev    | 2018-10-31 10:27:16.844 +08:00 [INF] - Created new message store
edgeHubDev    | 2018-10-31 10:27:16.851 +08:00 [INF] - Started task to cleanup processed and stale messages
edgeHubDev    | 2018-10-31 10:27:17.062 +08:00 [INF] - Initializing configuration
edgeHubDev    | 2018-10-31 10:27:17.579 +08:00 [INF] - Set the following 1 route(s) in edge hub
edgeHubDev    | 2018-10-31 10:27:17.581 +08:00 [INF] - r1: FROM /messages/modules/tempSensor/outputs/*
INTO $upstream
edgeHubDev    | 2018-10-31 10:27:17.582 +08:00 [INF] - Updated message store TTL to -1 seconds
edgeHubDev    | 2018-10-31 10:27:17.582 +08:00 [INF] - Updated the edge hub store and forward configuration
edgeHubDev    | 2018-10-31 10:27:17.583 +08:00 [INF] - Initialized edge hub configuration
edgeHubDev    | 2018-10-31 10:27:17.600 +08:00 [INF] - Starting timer to authenticate connections with
a period of 300 seconds
edgeHubDev    | 2018-10-31 10:27:17.731 +08:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
edgeHubDev    | 2018-10-31 10:27:17.749 +08:00 [INF] - Starting MQTT head
edgeHubDev    | 2018-10-31 10:27:17.860 +08:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT
head.
edgeHubDev    | 2018-10-31 10:27:17.953 +08:00 [INF] - Starting AMQP head
edgeHubDev    | 2018-10-31 10:27:17.972 +08:00 [INF] - Started MQTT head
edgeHubDev    | 2018-10-31 10:27:18.156 +08:00 [INF] - Started AMQP head
edgeHubDev    | 2018-10-31 10:27:18.159 +08:00 [INF] - Starting HTTP head
tempSensor    | [10/31/2018 02:27:18.245 AM] Main()
edgeHubDev    | 2018-10-31 10:27:18.309 +08:00 [INF] - User profile is available. Using '"C:\Users\ContainerUser\AppData\Local\ASP.NET\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
edgeHubDev    | 2018-10-31 10:27:18.345 +08:00 [INF] - Creating key {7e3c65b6-da26-4221-a05f-fa6434baf7db} with creation date 2018-10-31 02:27:18Z, activation date 2018-10-31 02:27:18Z, and expiration date
2019-01-29 02:27:18Z.
edgeHubDev    | 2018-10-31 10:27:18.396 +08:00 [INF] - Writing data to file '"C:\Users\ContainerUser\AppData\Local\ASP.NET\DataProtection-Keys\key-7e3c65b6-da26-4221-a05f-fa6434baf7db.xml"'.
tempSensor    | Using transport Amqp_Tcp_Only
edgeHubDev    | 2018-10-31 10:27:18.452 +08:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
edgeHubDev    | 2018-10-31 10:27:18.756 +08:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding
to endpoints defined in "UseKestrel()" instead.
edgeHubDev    | 2018-10-31 10:27:18.778 +08:00 [INF] - Started HTTP head
tempSensor    | Creating ModuleClient failed with exception System.TimeoutException: Operation timeout
expired.
tempSensor    |    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
tempSensor    |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType)
in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 100
tempSensor    | Retrying...
edgeHubDev    | 2018-10-31 10:32:17.591 +08:00 [INF] - Reauthenticating connected clients
tempSensor    | Creating ModuleClient failed with exception System.TimeoutException: Operation timeout
expired.
tempSensor    |    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
tempSensor    |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType)
in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 100
tempSensor    | Retrying...
edgeHubDev    | 2018-10-31 10:37:17.586 +08:00 [INF] - Reauthenticating connected clients
tempSensor    | Creating ModuleClient failed with exception System.TimeoutException: Operation timeout
expired.
tempSensor    |    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
tempSensor    |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType)
in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 100
tempSensor    | Retrying...
edgeHubDev    | 2018-10-31 10:42:17.602 +08:00 [INF] - Reauthenticating connected clients
tempSensor    | Creating ModuleClient failed with exception System.TimeoutException: Operation timeout
expired.
tempSensor    |    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
tempSensor    |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType)
in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 100
tempSensor    | Retrying...
edgeHubDev    | 2018-10-31 10:47:17.586 +08:00 [INF] - Reauthenticating connected clients
tempSensor    | Creating ModuleClient failed with exception System.TimeoutException: Operation timeout
expired.
tempSensor    |    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
tempSensor    |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType)
in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 100
edgeHubDev    | 2018-10-31 10:52:17.586 +08:00 [INF] - Reauthenticating connected clients
tempSensor    |
tempSensor    | Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
tempSensor    |    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
tempSensor    |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
tempSensor    | --- End of stack trace from previous location where exception was thrown ---
tempSensor    |    at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType)
in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 100
tempSensor    |    at SimulatedTemperatureSensor.Program.MainAsync() in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 69
tempSensor    |    --- End of inner exception stack trace ---
tempSensor    |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
tempSensor    |    at SimulatedTemperatureSensor.Program.Main() in C:\agent\_work\1\s\edge-modules\SimulatedTemperatureSensor\src\Program.cs:line 34
Gracefully stopping... (press Ctrl+C again to force)
Stopping tempSensor ... done
Stopping edgeHubDev ... done

Aborted!
```

**Comment by LazarusX** [comment]
Cannot reproduce this issue after restart Docker.
