### ISSUE TITLE
Multiple connections detected for device {name/module} causing lost ACKs

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/iotedgehubdev#106]
This may be related to issue #100 ... but it appears that the simulator Edge Hub is having issues is having troubles with multiple module routes. The configuration for the edge runtime routing is as follows given modules A, B, C:

A.Output1 -> B.Input1
B.Output1 -> C.Input1
C.Output2 -> A.Input2 (these are flow control messages that happen only very occasionally)

```
2018-11-03 18:11:43.902 +00:00 [INF] - New token received on the Cbs link
2018-11-03 18:11:43.903 +00:00 [INF] - Client edge/WebAppModule in device scope authenticated locally.
2018-11-03 18:11:43.903 +00:00 [INF] - Token updated for edge/WebAppModule
2018-11-03 18:11:43.912 +00:00 [INF] - New device connection for device edge/WebAppModule
2018-11-03 18:11:43.913 +00:00 [INF] - Closing AMQP device proxy for edge/WebAppModule because no handler was registered.
Microsoft.Azure.Devices.Edge.Hub.Core.MultipleConnectionsException: Multiple connections detected for device edge/WebAppModule
2018-11-03 18:11:43.917 +00:00 [INF] - Closing link ModuleMessages for edge/WebAppModule
2018-11-03 18:11:43.928 +00:00 [INF] - Bind device proxy for device edge/WebAppModule
2018-11-03 18:11:43.928 +00:00 [INF] - Initialized AMQP connection handler for edge/WebAppModule
2018-11-03 18:11:43.929 +00:00 [INF] - Opened link Events for edge/WebAppModule
2018-11-03 18:11:45.595 +00:00 [WRN] - Unable to send message to edge/WebAppModule because ModuleMessages link was not found.
2018-11-03 18:12:15.592 +00:00 [WRN] - Did not receive ack for message c855a408-3cab-4ef6-a7d1-a71ea03805b0 from device/module edge/WebAppModule
2018-11-03 18:12:15.596 +00:00 [WRN] - Error sending messages to module edge/WebAppModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 266
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 99
2018-11-03 18:12:16.712 +00:00 [WRN] - Unable to send message to edge/WebAppModule because ModuleMessages link was not found.
2018-11-03 18:12:46.710 +00:00 [WRN] - Did not receive ack for message eea78cbc-e2a5-4153-8c91-cde24ef54292 from device/module edge/WebAppModule
2018-11-03 18:12:46.710 +00:00 [WRN] - Error sending messages to module edge/WebAppModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 266
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 99
2018-11-03 18:12:48.616 +00:00 [WRN] - Unable to send message to edge/WebAppModule because ModuleMessages link was not found.
2018-11-03 18:13:18.629 +00:00 [WRN] - Did not receive ack for message a3ab05aa-51cf-4ddf-800b-b147a6e14731 from device/module edge/WebAppModule
2018-11-03 18:13:18.629 +00:00 [WRN] - Error sending messages to module edge/WebAppModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 266
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 99
2018-11-03 18:13:22.707 +00:00 [WRN] - Unable to send message to edge/WebAppModule because ModuleMessages link was not found.
2018-11-03 18:13:52.710 +00:00 [WRN] - Did not receive ack for message a97ec3a6-efe7-4c67-9e51-afd4bbf83b79 from device/module edge/WebAppModule
2018-11-03 18:13:52.711 +00:00 [WRN] - Error sending messages to module edge/WebAppModule
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 266
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.<>c__DisplayClass5_2.<<ProcessAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 99
```

**Comment by WilliamBerryiii** [comment]
On further investigation, the first message from C module back to A module is received and ack'ed correctly, however all subsequent calls fails.

**Comment by adashen** [comment]
Hi @WilliamBerryiii , from the log it seems edge/WebAppModule has opened multiple connections. Can you make sure there is no other instance of this module open?

**Comment by WilliamBerryiii** [comment]
That's what the error suggests, however this was a clean restart of the simulator ... all containers removed and brought back up from scratch.

**Comment by adashen** [comment]
@WilliamBerryiii I cannot reproduce the "Multiple connection detected" issue. Besides, if you could stable reproduce the multiple connection issue. Could you also retest it on real edge environment?

**Comment by WilliamBerryiii** [comment]
Ok, I'll put together a clean repro and add it to the case in a day or so.
