### ISSUE TITLE
can't get iotedgehubdev to work in a restricted environment where port 8883, 5671 is blocked 

### ISSUE THREAD

**Issue by buzzfrog** [Azure/iotedgehubdev#124]
I'm working with a industrial customer that have problem using this command. I thought that if these ports was not available, then it will try websockets. I have tried to set the UpstreamProtocol, but that doesn't help.

Here is the beginning of the log file:
```
Attaching to edgeHubDev, tempSensor, SampleModule
edgeHubDev      | [2018-11-08 07:30:36 : Starting Edge Hub
edgeHubDev      | [11/08/2018 07:30:36.674 AM] Edge Hub Main()
edgeHubDev      | [11/08/2018 07:30:36.876 AM] Found intermediate certificates.
tempSensor      | [2018-11-08 07:30:37 : Starting Module
tempSensor      | [11/08/2018 07:30:38.073 AM] Main()
edgeHubDev      | 2018-11-08 07:30:38.243 +00:00 [INF] - Created persistent store at /tmp/edgeHub
tempSensor      | Using transport Amqp_Tcp_Only
edgeHubDev      | 2018-11-08 07:30:38.321 +00:00 [INF] - Created device scope identities cache
edgeHubDev      | 2018-11-08 07:30:38.325 +00:00 [INF] - Starting Edge Hub
edgeHubDev      | 2018-11-08 07:30:38.326 +00:00 [INF] -
edgeHubDev      |         █████╗ ███████╗██╗   ██╗██████╗ ███████╗
edgeHubDev      |        ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
edgeHubDev      |        ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
edgeHubDev      |        ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
edgeHubDev      |        ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
edgeHubDev      |        ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
edgeHubDev      |
edgeHubDev      |  ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
edgeHubDev      |  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
edgeHubDev      |  ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
edgeHubDev      |  ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
edgeHubDev      |  ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
edgeHubDev      |  ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
edgeHubDev      |
edgeHubDev      | 2018-11-08 07:30:38.329 +00:00 [INF] - Version - 1.0.4.18259757 (2835ac47fbb944ba628a5cfe812ff394768842e0)
edgeHubDev      | 2018-11-08 07:30:38.341 +00:00 [INF] - Starting refresh of device scope identities cache
edgeHubDev      | 2018-11-08 07:30:38.364 +00:00 [INF] - Loaded server certificate with expiration date of "2019-11-06T07:21:33.0000000+00:00"
edgeHubDev      | 2018-11-08 07:30:38.560 +00:00 [INF] - Started task to cleanup processed and stale messages
edgeHubDev      | 2018-11-08 07:30:38.560 +00:00 [INF] - Created new message store
edgeHubDev      | 2018-11-08 07:30:38.987 +00:00 [INF] - Initializing configuration
edgeHubDev      | 2018-11-08 07:30:39.237 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
edgeHubDev      | 2018-11-08 07:30:39.372 +00:00 [INF] - Set the following 2 route(s) in edge hub
edgeHubDev      | 2018-11-08 07:30:39.377 +00:00 [INF] - r1: FROM /messages/modules/SampleModule/outputs/* INTO $upstream
edgeHubDev      | 2018-11-08 07:30:39.378 +00:00 [INF] - r2: FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO BrokeredEndpoint("/modules/SampleModule/inputs/input1")
edgeHubDev      | 2018-11-08 07:30:39.382 +00:00 [INF] - Updated message store TTL to -1 seconds
edgeHubDev      | 2018-11-08 07:30:39.383 +00:00 [INF] - Updated the edge hub store and forward configuration
edgeHubDev      | 2018-11-08 07:30:39.384 +00:00 [INF] - Initialized edge hub configuration
edgeHubDev      | 2018-11-08 07:30:39.439 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
edgeHubDev      | 2018-11-08 07:30:39.551 +00:00 [INF] - Scheduling server certificate renewal for "2019-11-06T07:19:03.0000667Z".
edgeHubDev      | 2018-11-08 07:30:39.553 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
edgeHubDev      | 2018-11-08 07:30:39.560 +00:00 [INF] - Starting MQTT head
edgeHubDev      | 2018-11-08 07:30:39.668 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
edgeHubDev      | 2018-11-08 07:30:39.747 +00:00 [INF] - Starting AMQP head
edgeHubDev      | 2018-11-08 07:30:39.755 +00:00 [INF] - Started MQTT head
edgeHubDev      | 2018-11-08 07:30:39.896 +00:00 [INF] - Started AMQP head
edgeHubDev      | 2018-11-08 07:30:39.910 +00:00 [INF] - Starting HTTP head
edgeHubDev      | 2018-11-08 07:30:40.079 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
edgeHubDev      | 2018-11-08 07:30:40.109 +00:00 [INF] - Creating key {3f90f106-f692-4e0f-8b49-edd1fbd6e8b4} with creation date 2018-11-08 07:30:40Z, activation date 2018-11-08 07:30:40Z, and expiration date 2019-02-06 07:30:40Z.
edgeHubDev      | 2018-11-08 07:30:40.124 +00:00 [WRN] - No XML encryptor configured. Key {3f90f106-f692-4e0f-8b49-edd1fbd6e8b4} may be persisted to storage in unencrypted form.
edgeHubDev      | 2018-11-08 07:30:40.130 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-3f90f106-f692-4e0f-8b49-edd1fbd6e8b4.xml"'.
edgeHubDev      | 2018-11-08 07:30:40.621 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
edgeHubDev      | 2018-11-08 07:30:40.670 +00:00 [INF] - Started HTTP head
edgeHubDev      | 2018-11-08 07:30:40.691 +00:00 [INF] - New token received on the Cbs link
edgeHubDev      | 2018-11-08 07:30:40.957 +00:00 [WRN] - Error while refreshing the service identity for dagk-dev-001/tempSensor
edgeHubDev      | Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiException: Message: Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized, Content: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:60e6fac57a4844bc81088273e5293709-G:4-TimeStamp:11/08/2018 07:30:42"}
edgeHubDev      |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 115
edgeHubDev      |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 85
edgeHubDev      |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs:line 77
edgeHubDev      |    at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hu
```

**Comment by adashen** [comment]
@buzzfrog several questions
1. Can you use the latest iotedgehubdev to try again? 
pip install --upgrade iotedgehubdev 
From the log, it seems you are using the previous version and the warning has been fixed in the latest version. (0.5.0)

2. As you mentioned the port 8883, 5671 is blocked. Actually if your leaf device doesn't use these port to talk to edgeHubDev, you can just don't expose these ports. Just remove the exposing port part of createOptions in your deployment manifest.
