### ISSUE TITLE
Device impersonation does not send event to IoT Hub

### ISSUE THREAD

**Issue by fbeltrao** [Azure/iotedgehubdev#143]
In a module that impersonates leaf devices, sending device to cloud messages does not seem to work. All other operations seem to work (get twin, update twin, c2d messages).

See the sample module located at: https://github.com/fbeltrao/Samples/tree/master/IoTEdgeHubDevD2C/iotedgehubdevd2c

What the sample module does:

- While true
  - Creates a `DeviceClient` connection, gets twin, updates twin, gets c2d message, sends d2c message
  - Every 3 executions of the loop it will switch between connecting through edgeHubDev or not (adding `;GatewayHostName=localhost` to connection string).

Expected behavior is that device to cloud messages would arrive in IoT Hub, but they don't. They do arrive when not connecting through edgeHubDev. It is important to notice that I am running the sample from a Mac, where the ca certificate had to be added to keychain.

**Module logs**

```text
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
IoT Hub module client initialized.
[Gateway: True] Device client created
[Gateway: True] Twin properties read, counter: 0
[Gateway: True] Reported properties updated, counter: 1
[Gateway: True] Sent event 1 <- THIS DOES NOT REACH IOT HUB
[Gateway: True] Device client created
[Gateway: True] Twin properties read, counter: 1
[Gateway: True] Reported properties updated, counter: 2
[Gateway: True] Sent event 2 <- THIS DOES NOT REACH IOT HUB
[Gateway: False] Device client created
[Gateway: False] Twin properties read, counter: 2
[Gateway: False] Reported properties updated, counter: 3
[Gateway: False] Sent event 3 <- THIS DOES REACH IOT HUB
[Gateway: False] Device client created
[Gateway: False] Twin properties read, counter: 3
[Gateway: False] Reported properties updated, counter: 4
[Gateway: False] Sent event 4 <- THIS DOES REACH IOT HUB
The program '[4944] TransparentGatewayModule.dll' has exited with code 0 (0x0).
```

**edgeHubDev logs**

```text
2018-12-16 16:44:34.151 +00:00 [INF] - New token received on the Cbs link
2018-12-16 16:44:34.152 +00:00 [INF] - Client fbesimulatededge/target in device scope authenticated locally.
2018-12-16 16:44:34.152 +00:00 [INF] - Token updated for fbesimulatededge/target
2018-12-16 16:44:34.239 +00:00 [INF] - New device connection for device fbesimulatededge/target
2018-12-16 16:44:34.239 +00:00 [INF] - Bind device proxy for device fbesimulatededge/target
2018-12-16 16:44:34.239 +00:00 [INF] - Initialized AMQP connection handler for fbesimulatededge/target
2018-12-16 16:44:34.239 +00:00 [INF] - Opened link Events for fbesimulatededge/target
2018-12-16 16:44:47.060 +00:00 [INF] - New token received on the Cbs link
2018-12-16 16:44:47.250 +00:00 [WRN] - Received null device scope result for iotedgehubdev4test2
2018-12-16 16:44:47.250 +00:00 [INF] - Service identity for iotedgehubdev4test2 was removed from device scope, dropping client connection.
2018-12-16 16:44:47.250 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedgehubdev4test2 via AMQP...
2018-12-16 16:44:47.463 +00:00 [INF] - New token requested by client iotedgehubdev4test2, but using existing token as it is usable.
2018-12-16 16:44:47.709 +00:00 [INF] - Cloud connection for iotedgehubdev4test2 is True
2018-12-16 16:44:47.709 +00:00 [INF] - Created cloud proxy for client iotedgehubdev4test2 via AMQP, with client operation timeout 20000.
2018-12-16 16:44:47.709 +00:00 [INF] - Initialized cloud proxy 9158d707-1c2b-4b1a-92d1-d28044b6cc76 for iotedgehubdev4test2
2018-12-16 16:44:47.709 +00:00 [INF] - Created cloud connection for client iotedgehubdev4test2
2018-12-16 16:44:47.709 +00:00 [INF] - New cloud connection created for device iotedgehubdev4test2
2018-12-16 16:44:47.709 +00:00 [INF] - Authenticated iotedgehubdev4test2 with IotHub
2018-12-16 16:44:47.709 +00:00 [INF] - Token updated for iotedgehubdev4test2
2018-12-16 16:44:47.740 +00:00 [INF] - New device connection for device iotedgehubdev4test2
2018-12-16 16:44:47.740 +00:00 [INF] - Bind device proxy for device iotedgehubdev4test2
2018-12-16 16:44:47.740 +00:00 [INF] - Initialized AMQP connection handler for iotedgehubdev4test2
2018-12-16 16:44:47.740 +00:00 [INF] - Opened link TwinReceiving for iotedgehubdev4test2
2018-12-16 16:44:47.746 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iotedgehubdev4test2.
2018-12-16 16:44:47.834 +00:00 [INF] - Opened link TwinSending for iotedgehubdev4test2
2018-12-16 16:44:50.649 +00:00 [INF] - Processing subscription C2D for client iotedgehubdev4test2.
2018-12-16 16:44:50.649 +00:00 [INF] - Start listening for C2D messages for device iotedgehubdev4test2
2018-12-16 16:44:50.649 +00:00 [INF] - Opened link C2D for iotedgehubdev4test2
2018-12-16 16:44:52.750 +00:00 [INF] - Opened link Events for iotedgehubdev4test2
2018-12-16 16:44:56.868 +00:00 [INF] - Closing link Events for iotedgehubdev4test2
2018-12-16 16:44:56.869 +00:00 [INF] - Closing link C2D for iotedgehubdev4test2
2018-12-16 16:44:56.886 +00:00 [INF] - Closing link TwinSending for iotedgehubdev4test2
2018-12-16 16:44:56.887 +00:00 [INF] - Closing link TwinReceiving for iotedgehubdev4test2
2018-12-16 16:44:56.887 +00:00 [INF] - Setting proxy inactive for iotedgehubdev4test2.
2018-12-16 16:44:56.887 +00:00 [INF] - Device connection removed for device iotedgehubdev4test2
2018-12-16 16:44:56.887 +00:00 [INF] - Remove device connection for device iotedgehubdev4test2
2018-12-16 16:44:57.103 +00:00 [INF] - New token received on the Cbs link
2018-12-16 16:44:57.103 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedgehubdev4test2 via AMQP...
2018-12-16 16:44:57.103 +00:00 [INF] - New token requested by client iotedgehubdev4test2, but using existing token as it is usable.
2018-12-16 16:44:57.296 +00:00 [INF] - Cloud connection for iotedgehubdev4test2 is True
2018-12-16 16:44:57.296 +00:00 [INF] - Created cloud proxy for client iotedgehubdev4test2 via AMQP, with client operation timeout 20000.
2018-12-16 16:44:57.296 +00:00 [INF] - Initialized cloud proxy c9114eee-71cb-435d-8ca9-d7cb643219c0 for iotedgehubdev4test2
2018-12-16 16:44:57.296 +00:00 [INF] - Closing receiver in cloud proxy 9158d707-1c2b-4b1a-92d1-d28044b6cc76 for iotedgehubdev4test2
2018-12-16 16:45:17.299 +00:00 [INF] - Cloud message receiver stopped for device iotedgehubdev4test2 in cloud proxy 9158d707-1c2b-4b1a-92d1-d28044b6cc76
2018-12-16 16:45:17.299 +00:00 [INF] - Closed cloud proxy 9158d707-1c2b-4b1a-92d1-d28044b6cc76 for iotedgehubdev4test2
2018-12-16 16:45:17.300 +00:00 [INF] - New cloud connection created for device iotedgehubdev4test2
2018-12-16 16:45:17.300 +00:00 [INF] - Authenticated iotedgehubdev4test2 with IotHub
2018-12-16 16:45:17.300 +00:00 [INF] - Token updated for iotedgehubdev4test2
2018-12-16 16:45:17.364 +00:00 [INF] - New device connection for device iotedgehubdev4test2
2018-12-16 16:45:17.364 +00:00 [INF] - Bind device proxy for device iotedgehubdev4test2
2018-12-16 16:45:17.364 +00:00 [INF] - Initialized AMQP connection handler for iotedgehubdev4test2
2018-12-16 16:45:17.364 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iotedgehubdev4test2.
2018-12-16 16:45:17.367 +00:00 [INF] - Opened link TwinReceiving for iotedgehubdev4test2
2018-12-16 16:45:37.359 +00:00 [INF] - Opened link TwinSending for iotedgehubdev4test2
2018-12-16 16:45:47.382 +00:00 [INF] - Closing link TwinSending for iotedgehubdev4test2
2018-12-16 16:45:47.382 +00:00 [INF] - Closing link TwinReceiving for iotedgehubdev4test2
2018-12-16 16:45:47.382 +00:00 [INF] - Setting proxy inactive for iotedgehubdev4test2.
2018-12-16 16:45:47.382 +00:00 [INF] - Device connection removed for device iotedgehubdev4test2
2018-12-16 16:45:47.382 +00:00 [INF] - Remove device connection for device iotedgehubdev4test2
2018-12-16 16:45:47.689 +00:00 [INF] - New token received on the Cbs link
2018-12-16 16:45:47.690 +00:00 [INF] - Attempting to connect to IoT Hub for client iotedgehubdev4test2 via AMQP...
2018-12-16 16:45:47.915 +00:00 [INF] - New token requested by client iotedgehubdev4test2, but using existing token as it is usable.
2018-12-16 16:45:48.191 +00:00 [INF] - Cloud connection for iotedgehubdev4test2 is True
2018-12-16 16:45:48.191 +00:00 [INF] - Created cloud proxy for client iotedgehubdev4test2 via AMQP, with client operation timeout 20000.
2018-12-16 16:45:48.191 +00:00 [INF] - Initialized cloud proxy 498f5629-01f3-44c2-8ad0-d7f41e3f7292 for iotedgehubdev4test2
2018-12-16 16:45:48.192 +00:00 [INF] - Closing receiver in cloud proxy c9114eee-71cb-435d-8ca9-d7cb643219c0 for iotedgehubdev4test2
2018-12-16 16:45:48.192 +00:00 [INF] - Closed cloud proxy c9114eee-71cb-435d-8ca9-d7cb643219c0 for iotedgehubdev4test2
2018-12-16 16:45:48.192 +00:00 [INF] - New cloud connection created for device iotedgehubdev4test2
2018-12-16 16:45:48.192 +00:00 [INF] - Authenticated iotedgehubdev4test2 with IotHub
2018-12-16 16:45:48.192 +00:00 [INF] - Token updated for iotedgehubdev4test2
2018-12-16 16:45:48.202 +00:00 [INF] - New device connection for device iotedgehubdev4test2
2018-12-16 16:45:48.202 +00:00 [INF] - Bind device proxy for device iotedgehubdev4test2
2018-12-16 16:45:48.202 +00:00 [INF] - Initialized AMQP connection handler for iotedgehubdev4test2
2018-12-16 16:45:48.202 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client iotedgehubdev4test2.
2018-12-16 16:45:48.204 +00:00 [INF] - Opened link TwinReceiving for iotedgehubdev4test2
2018-12-16 16:45:48.287 +00:00 [INF] - Opened link TwinSending for iotedgehubdev4test2
2018-12-16 16:45:49.505 +00:00 [WRN] - Unable to send twin update to iotedgehubdev4test2 because ModuleMessages link was not found.
2018-12-16 16:45:49.505 +00:00 [WRN] - Error processing message in TwinReceiving link for iotedgehubdev4test2
Microsoft.Azure.Amqp.AmqpException: 'receiver299' is closed
   at Microsoft.Azure.Amqp.AmqpObject.ThrowIfClosed()
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.EdgeReceivingAmqpLink.DisposeMessage(AmqpMessage amqpMessage, Outcome outcome, Boolean settled, Boolean batchable) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/EdgeAmqpLink.cs:line 50
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.ReceivingLinkHandler.ProcessMessageAsync(AmqpMessage amqpMessage) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/ReceivingLinkHandler.cs:line 85
2018-12-16 16:45:51.923 +00:00 [INF] - Processing subscription C2D for client iotedgehubdev4test2.
2018-12-16 16:45:51.923 +00:00 [INF] - Start listening for C2D messages for device iotedgehubdev4test2
2018-12-16 16:45:51.923 +00:00 [INF] - Opened link C2D for iotedgehubdev4test2
2018-12-16 16:45:53.947 +00:00 [INF] - Opened link Events for iotedgehubdev4test2
2018-12-16 16:45:58.046 +00:00 [INF] - Closing link Events for iotedgehubdev4test2
2018-12-16 16:45:58.046 +00:00 [INF] - Closing link C2D for iotedgehubdev4test2
2018-12-16 16:45:58.046 +00:00 [INF] - Closing link TwinSending for iotedgehubdev4test2
2018-12-16 16:45:58.047 +00:00 [INF] - Closing link TwinReceiving for iotedgehubdev4test2
2018-12-16 16:45:58.047 +00:00 [INF] - Setting proxy inactive for iotedgehubdev4test2.
2018-12-16 16:45:58.047 +00:00 [INF] - Device connection removed for device iotedgehubdev4test2
2018-12-16 16:45:58.047 +00:00 [INF] - Remove device connection for device iotedgehubdev4test2
2018-12-16 16:46:14.200 +00:00 [INF] - Closing link Events for fbesimulatededge/target
2018-12-16 16:46:14.200 +00:00 [INF] - Setting proxy inactive for fbesimulatededge/target.
2018-12-16 16:46:14.200 +00:00 [INF] - Device connection removed for device fbesimulatededge/target
2018-12-16 16:46:14.200 +00:00 [INF] - Remove device connection for device fbesimulatededge/target
2018-12-16 16:46:53.475 +00:00 [INF] - Reauthenticating connected clients
```

**Device to cloud monitor**

```
[IoTHubMonitor] Start monitoring D2C message for [iotedgehubdev4test2] ...
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [3] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [2] for consumerGroup [$Default]
[IoTHubMonitor] [5:46:03 PM] Message received from [iotedgehubdev4test2]:
3
[IoTHubMonitor] [5:46:12 PM] Message received from [iotedgehubdev4test2]:
4
```

Please let me know if you need more information.

**Comment by fbeltrao** [comment]
@adashen thanks, that was the problem. 
Using this deployment json file worked for me:

```json
{
    "moduleContent": {
        "$edgeAgent": {
            "properties.desired": {
                "schemaVersion": "1.0",
                "runtime": {
                    "type": "docker",
                    "settings": {
                        "minDockerVersion": "v1.25",
                        "loggingOptions": "",
                        "registryCredentials": {}
                    }
                },
                "systemModules": {
                    "edgeAgent": {
                        "type": "docker",
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
                            "createOptions": ""
                        }
                    },
                    "edgeHub": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
                            "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}], \"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
                        }
                    }
                },
                "modules": {
                    "input": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-testing-utility:1.0.0-rc1"
                        }
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "schemaVersion": "1.0",
                "routes": {
                    "sensorToIoTHub": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO $upstream"
                },
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        }
    }
}
```

Perhaps adding an example to the documenation using -d to start will be helpfull.
