### ISSUE TITLE
 iotedgehubdev start -H work error: environment can only contain strings

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#165]
repro on 0.7.0-rc

```
PS C:\WINDOWS\system32> iotedgehubdev start -H "npipe:////./pipe/iotedge_moby_engine"
Traceback (most recent call last):
  File "c:\python27\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\python27\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp20127
Logged from file network.py, line 98
ERROR: environment can only contain strings
```

![image](https://user-images.githubusercontent.com/35018765/51580132-5c440980-1efe-11e9-98e6-332f93420ea8.png)

**Comment by adashen** [comment]
@czgtest Please make sure whether this has been fixed. If so please help to close it.

**Comment by czgtest** [comment]
now ,it fix work ,
![image](https://user-images.githubusercontent.com/35018765/55211190-f2a9e980-5225-11e9-9a5c-50f084a0e03c.png)
