### ISSUE TITLE
iotedgehubdev can't work after install through GitHub  on Ubuntu/Mac

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#215]
repro on : ubuntu/mac
python: 2.7.15 / 2.7.14
step:
1. pip install git+https://github.com/Azure/iotedgehubdev.git@master
2. iotedgehubdev --version

iotedgetest@iotedgetest-desktop:~$ iotedgehubdev --version
Traceback (most recent call last):
  File "/usr/local/bin/iotedgehubdev", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 4.2b4 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('PyYAML<4,>=3.10'), set(['docker-compose']))

**Comment by adashen** [comment]
@czgtest it is a python package version issue. Can you try to install it on a clean ubuntu machine?

**Comment by czgtest** [comment]
https://github.com/cloud-custodian/cloud-custodian/issues/3413

**Comment by czgtest** [comment]
on clean Ubuntu machine ，this issue is not repro on.

on Mac machine. we can use bellow steps to resolve this issue. 

sudo pip uninstall azure-cli-core 2.0.49
sudo pip install docker-compose==1.24.0
sudo pip install git+https://github.com/Azure/iotedgehubdev.git@master
