### ISSUE TITLE
TLS authentication error - The remote certificate is invalid

### ISSUE THREAD

**Issue by AMCN41R** [Azure/iotedgehubdev#269]
Hi

I'm running into the following exception when trying to run my custom modules using the dev tool:
```
System.Security.Authentication.AuthenticationException: TLS authentication error.
 ---> System.Net.WebSockets.WebSocketException (203): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

I have created a brand new device in Azure IoT Hub, and run `iotedgehubdev setup` again, and experience the same issue.

Running in docker on Windows 10
Custom modules are C#
iotedgehubdev --version: 0.13.0
Microsoft.Azure.Devices.Client nuget package version: 1.24.0
edgeAgent: 1.0.9
edgeHub: 1.0.9

I am running the following command...
```
iotedgehubdev start -d .\src\Edge\config\deployment.debug.amd64.json -v
```

edgeHubDev boots up, but when my custom moduels attempt to send a message to `$upstream`, I see this error. What am I missing?

Full logs...
```
Attaching to edgeHubDev, device, cbusemu, scheduler
edgeHubDev    | 2020-04-09 03:28:03  Starting Edge Hub
edgeHubDev    | 2020-04-09 03:28:03.441 +00:00 Edge Hub Main()
edgeHubDev    | <6> 2020-04-09 03:28:03.738 +00:00 [INF] - Installing certificates [CN=Edge Agent CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:04/08/2021 13:26:40],[CN=Edge Test Device CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:04/09/2021 13:26:38] to Root
edgeHubDev    | <6> 2020-04-09 03:28:03.774 +00:00 [INF] - Installing certificates  to Root
edgeHubDev    | <6> 2020-04-09 03:28:05.325 +00:00 [INF] - Created persistent store at /tmp/edgeHub
edgeHubDev    | <6> 2020-04-09 03:28:05.347 +00:00 [INF] - Created device scope identities cache
edgeHubDev    | <6> 2020-04-09 03:28:05.355 +00:00 [INF] - Initializing Edge Hub
edgeHubDev    | <6> 2020-04-09 03:28:05.351 +00:00 [INF] - Starting refresh of device scope identities cache
edgeHubDev    | <6> 2020-04-09 03:28:05.362 +00:00 [INF] -
edgeHubDev    |         █████╗ ███████╗██╗   ██╗██████╗ ███████╗
edgeHubDev    |        ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
edgeHubDev    |        ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
edgeHubDev    |        ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
edgeHubDev    |        ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
edgeHubDev    |        ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
edgeHubDev    |
edgeHubDev    |  ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
edgeHubDev    |  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
edgeHubDev    |  ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
edgeHubDev    |  ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
edgeHubDev    |  ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
edgeHubDev    |  ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
edgeHubDev    |
edgeHubDev    | <6> 2020-04-09 03:28:05.364 +00:00 [INF] - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
edgeHubDev    | <6> 2020-04-09 03:28:05.364 +00:00 [INF] - OptimizeForPerformance=True
edgeHubDev    | <6> 2020-04-09 03:28:05.369 +00:00 [INF] - Loaded server certificate with expiration date of "2021-04-07T13:26:40.0000000+00:00"
edgeHubDev    | <6> 2020-04-09 03:28:05.465 +00:00 [INF] - Created new message store
edgeHubDev    | <6> 2020-04-09 03:28:05.469 +00:00 [INF] - Started task to cleanup processed and stale messages
edgeHubDev    | <6> 2020-04-09 03:28:05.696 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
edgeHubDev    | <6> 2020-04-09 03:28:05.787 +00:00 [INF] - Initialized storing twin manager
edgeHubDev    | <6> 2020-04-09 03:28:05.805 +00:00 [INF] - Initializing configuration
edgeHubDev    | <6> 2020-04-09 03:28:06.040 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
edgeHubDev    | <4> 2020-04-09 03:28:06.069 +00:00 [WRN] - Empty edge hub configuration received. Ignoring...
edgeHubDev    | <4> 2020-04-09 03:28:06.175 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
edgeHubDev    | <6> 2020-04-09 03:28:06.391 +00:00 [INF] - Set the following 4 route(s) in edge hub
edgeHubDev    | <6> 2020-04-09 03:28:06.391 +00:00 [INF] - r1: FROM /messages/modules/scheduler/outputs/hub INTO $upstream
edgeHubDev    | <6> 2020-04-09 03:28:06.391 +00:00 [INF] - r2: FROM /messages/modules/device/outputs/hub INTO $upstream
edgeHubDev    | <6> 2020-04-09 03:28:06.391 +00:00 [INF] - r3: FROM /messages/modules/device/outputs/scheduler INTO BrokeredEndpoint("/modules/scheduler/inputs/hub")
edgeHubDev    | <6> 2020-04-09 03:28:06.391 +00:00 [INF] - r4: FROM /messages/modules/device/outputs/scheduler-info INTO BrokeredEndpoint("/modules/scheduler/inputs/info")
edgeHubDev    | <6> 2020-04-09 03:28:06.400 +00:00 [INF] - Updated message store TTL to -1 seconds
edgeHubDev    | <6> 2020-04-09 03:28:06.401 +00:00 [INF] - Updated the edge hub store and forward configuration
edgeHubDev    | <6> 2020-04-09 03:28:06.426 +00:00 [INF] - Started operation Get EdgeHub config
edgeHubDev    | <6> 2020-04-09 03:28:06.427 +00:00 [INF] - Initialized edge hub configuration
edgeHubDev    | <6> 2020-04-09 03:28:06.456 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
edgeHubDev    | <6> 2020-04-09 03:28:06.568 +00:00 [INF] - Scheduling server certificate renewal for "2021-04-07T13:24:10.0000805Z".
edgeHubDev    | <6> 2020-04-09 03:28:06.571 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
edgeHubDev    | <6> 2020-04-09 03:28:06.577 +00:00 [INF] - Starting MQTT head
edgeHubDev    | <6> 2020-04-09 03:28:06.620 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
edgeHubDev    | <6> 2020-04-09 03:28:06.694 +00:00 [INF] - Starting AMQP head
edgeHubDev    | <6> 2020-04-09 03:28:06.719 +00:00 [INF] - Started MQTT head
edgeHubDev    | <6> 2020-04-09 03:28:06.801 +00:00 [INF] - Started AMQP head
edgeHubDev    | <6> 2020-04-09 03:28:06.805 +00:00 [INF] - Starting HTTP head
edgeHubDev    | <6> 2020-04-09 03:28:06.915 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
edgeHubDev    | <6> 2020-04-09 03:28:06.943 +00:00 [INF] - Creating key {4376448d-b0fc-42dc-b521-e435fb2413c4} with creation date 2020-04-09 03:28:06Z, activation date 2020-04-09 03:28:06Z, and expiration date 2020-07-08 03:28:06Z.
edgeHubDev    | <4> 2020-04-09 03:28:06.958 +00:00 [WRN] - No XML encryptor configured. Key {4376448d-b0fc-42dc-b521-e435fb2413c4} may be persisted to storage in unencrypted form.
edgeHubDev    | <6> 2020-04-09 03:28:06.963 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-4376448d-b0fc-42dc-b521-e435fb2413c4.xml"'.
edgeHubDev    | <4> 2020-04-09 03:28:07.312 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
edgeHubDev    | <6> 2020-04-09 03:28:07.340 +00:00 [INF] - Started HTTP head
scheduler     | fail: SANDSTORM[0]
scheduler     |       2020-04-09 03:28:07Z | Error sending event of type 'MessageEnvelope' to 'hub'. Retrying in 0.5.
scheduler     | System.Security.Authentication.AuthenticationException: TLS authentication error.
scheduler     |  ---> System.Net.WebSockets.WebSocketException (203): Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
scheduler     |  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
scheduler     |    at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
scheduler     |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
scheduler     |    at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
scheduler     | --- End of stack trace from previous location where exception was thrown ---
scheduler     |    at System.Net.Security.SslStream.ThrowIfExceptional()
scheduler     |    at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
scheduler     |    at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
scheduler     |    at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
scheduler     |    at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
scheduler     |    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
scheduler     | --- End of stack trace from previous location where exception was thrown ---
scheduler     |    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
scheduler     |    --- End of inner exception stack trace ---
scheduler     |    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
scheduler     |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
scheduler     |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
scheduler     |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
scheduler     |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
scheduler     |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
scheduler     |    at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
scheduler     |    at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
scheduler     |    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketAsync(Uri websocketUri, TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.CreateClientWebSocketTransportAsync(TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTTransport.InitializeAsync(TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpIoTConnector.OpenConnectionAsync(TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.EnsureConnectionAsync(TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.OpenSessionAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
scheduler     | --- End of stack trace from previous location where exception was thrown ---
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
scheduler     |    --- End of inner exception stack trace ---
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
scheduler     | --- End of stack trace from previous location where exception was thrown ---
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
scheduler     | --- End of stack trace from previous location where exception was thrown ---
scheduler     |    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
scheduler     |    at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
scheduler     |    at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
scheduler     | --- End of stack trace from previous location where exception was thrown ---
scheduler     |    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
```

**Comment by SLdragon** [comment]
Hi, @AMCN41R , from the error message, seems that it is related to the certificate, 
for certificate issue, you can try to resetup iotedgehubdev:
- Remove the iotedgehubdev config folder in "C:\ProgramData\iotedgehubdev"
- Re-setup iotedgehubdev in the vscode through command palette "Azure IoT Edge: Set up IoT Edge simulator"
- If the above not works, try different version of the package "Microsoft.Azure.Devices.Client" in the "modules/SampleModule/SampleMoudule.csproj"
-
-     <PackageReference Include="Microsoft.Azure.Devices.Client" Version="1.*" />

Another reason is maybe your system time inside the container is not correct, you can follow this link to fix it: https://github.com/Azure/iotedgehubdev/issues/266#issuecomment-595233648

if you are under a proxy, you can try to shutdown the proxy and try again.

**Comment by AMCN41R** [comment]
Hi @SLdragon, thanks for the quick response. Turns out it was the time drift issue.

I toggled the time time synchronization option on the docker vm integration services settings as described in [#266 (comment)](https://github.com/Azure/iotedgehubdev/issues/266#issuecomment-595233648).

Thanks for your help.
