### ISSUE TITLE
Unable to authenticate client module due to outdated token

### ISSUE THREAD

**Issue by gerlitm101** [Azure/iotedgehubdev#283]
Hello Everyone,

I try to build and run iotedge modules in simulator using Visual Studio 2019 and **Windows Containers**. My assumption is that the sas token requested by edgehubdev container is outdated and so the modules are not able to authenticate. Maybe the windows container or windows image has wrong time zone or no time synchronization with my local machine? 

I'm not very experienced in creating issues on github so please let me know if there are additional information you require from my side.

Docker Desktop CE Version: 2.3.0.4 (46911)
Docker Engine: 19.03.12

**Console Output**
```
Network azure-iot-edge-dev is external, skipping
Pulling edgeHubDev ... 
Pulling edgeHubDev ... pulling from azureiotedge-hub
Pulling edgeHubDev ... digest: sha256:81cc93b133974630a8...
Pulling edgeHubDev ... status: image is up to date for m...
Pulling edgeHubDev ... done
Creating edgeHubDev ... 
Creating edgeHubDev ... done
Creating SimulatedTemperatureSensor ... 
Creating IotEdgeModule1             ... 
Creating SimulatedTemperatureSensor ... done
Creating IotEdgeModule1             ... done
Attaching to edgeHubDev, SimulatedTemperatureSensor, IotEdgeModule1
edgeHubDev                    | 2020-09-07 14:55:35.071 +00:00 Edge Hub Main()
edgeHubDev                    | <6> 2020-09-07 16:55:35.916 +02:00 [INF] - Installing certificates [CN=Edge Agent CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:9/6/2021 3:57:26 PM],[CN=Edge Test Device CA, OU=Default Edge Organization, O=Default Edge Organization, L=Redmond, S=Washington, C=US:9/7/2021 3:57:10 PM] to CertificateAuthority
edgeHubDev                    | <6> 2020-09-07 16:55:36.025 +02:00 [INF] - Installing certificates  to CertificateAuthority
SimulatedTemperatureSensor    | SimulatedTemperatureSensor Main() started.
edgeHubDev                    | <6> 2020-09-07 16:55:38.023 +02:00 [INF] - Detected proxy http://host.docker.internal:3128/
SimulatedTemperatureSensor    | Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
SimulatedTemperatureSensor    | To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
SimulatedTemperatureSensor    | Information: Trying to initialize module client using transport type [Amqp_Tcp_Only].
edgeHubDev                    | <6> 2020-09-07 16:55:38.787 +02:00 [INF] - Created persistent store at C:\Windows\TEMP\edgeHub
edgeHubDev                    | <6> 2020-09-07 16:55:38.810 +02:00 [INF] - Created device scope identities cache
edgeHubDev                    | <6> 2020-09-07 16:55:38.818 +02:00 [INF] - Starting refresh of device scope identities cache
edgeHubDev                    | <6> 2020-09-07 16:55:38.821 +02:00 [INF] - Initializing Edge Hub
edgeHubDev                    | <6> 2020-09-07 16:55:38.822 +02:00 [INF] - 
edgeHubDev                    |         ?????? ???????????   ?????????? ????????
edgeHubDev                    |        ???????????????????   ???????????????????
edgeHubDev                    |        ????????  ????? ???   ?????????????????
edgeHubDev                    |        ???????? ?????  ???   ?????????????????
edgeHubDev                    |        ???  ???????????????????????  ???????????
edgeHubDev                    |        ???  ??????????? ??????? ???  ???????????
edgeHubDev                    | 
edgeHubDev                    |  ??? ??????? ?????????    ???????????????  ??????? ????????
edgeHubDev                    |  ?????????????????????    ???????????????????????? ????????
edgeHubDev                    |  ??????   ???   ???       ??????  ???  ??????  ??????????
edgeHubDev                    |  ??????   ???   ???       ??????  ???  ??????   ?????????
edgeHubDev                    |  ????????????   ???       ?????????????????????????????????
edgeHubDev                    |  ??? ???????    ???       ???????????????  ??????? ????????
edgeHubDev                    | 
edgeHubDev                    | <6> 2020-09-07 16:55:38.824 +02:00 [INF] - Version - 1.0.9.4.32971639 (12d55e582cc7ce95c8abfe11eddfbbc938ed6001)
edgeHubDev                    | <6> 2020-09-07 16:55:38.824 +02:00 [INF] - OptimizeForPerformance=True
edgeHubDev                    | <6> 2020-09-07 16:55:38.824 +02:00 [INF] - MessageAckTimeoutSecs=30
edgeHubDev                    | <6> 2020-09-07 16:55:38.827 +02:00 [INF] - Loaded server certificate with expiration date of "2021-09-05T15:57:27.0000000+02:00"
edgeHubDev                    | <6> 2020-09-07 16:55:38.886 +02:00 [INF] - Created new message store
edgeHubDev                    | <6> 2020-09-07 16:55:38.899 +02:00 [INF] - Started task to cleanup processed and stale messages
edgeHubDev                    | <6> 2020-09-07 16:55:39.086 +02:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
edgeHubDev                    | <6> 2020-09-07 16:55:39.133 +02:00 [INF] - Initialized storing twin manager
edgeHubDev                    | <6> 2020-09-07 16:55:39.156 +02:00 [INF] - Initializing configuration
edgeHubDev                    | <6> 2020-09-07 16:55:39.342 +02:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
edgeHubDev                    | <4> 2020-09-07 16:55:39.361 +02:00 [WRN] - Empty edge hub configuration received. Ignoring...
edgeHubDev                    | <6> 2020-09-07 16:55:39.535 +02:00 [INF] - Set the following 2 route(s) in edge hub
edgeHubDev                    | <6> 2020-09-07 16:55:39.535 +02:00 [INF] - r1: FROM /messages/modules/IotEdgeModule1/outputs/* INTO $upstream
edgeHubDev                    | <6> 2020-09-07 16:55:39.535 +02:00 [INF] - r2: FROM /messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput INTO BrokeredEndpoint("/modules/IotEdgeModule1/inputs/input1")
edgeHubDev                    | <6> 2020-09-07 16:55:39.537 +02:00 [INF] - Updated message store TTL to -1 seconds
edgeHubDev                    | <6> 2020-09-07 16:55:39.537 +02:00 [INF] - Updated the edge hub store and forward configuration
edgeHubDev                    | <6> 2020-09-07 16:55:39.547 +02:00 [INF] - Started operation Get EdgeHub config
edgeHubDev                    | <6> 2020-09-07 16:55:39.548 +02:00 [INF] - Initialized edge hub configuration
edgeHubDev                    | <6> 2020-09-07 16:55:39.563 +02:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
edgeHubDev                    | <6> 2020-09-07 16:55:39.661 +02:00 [INF] - Scheduling server certificate renewal for "2021-09-05T15:54:57.0000667Z".
edgeHubDev                    | <6> 2020-09-07 16:55:39.662 +02:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
edgeHubDev                    | <6> 2020-09-07 16:55:39.670 +02:00 [INF] - Starting MQTT head
edgeHubDev                    | <6> 2020-09-07 16:55:39.703 +02:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
edgeHubDev                    | <6> 2020-09-07 16:55:39.771 +02:00 [INF] - Starting AMQP head
edgeHubDev                    | <6> 2020-09-07 16:55:39.784 +02:00 [INF] - Started MQTT head
edgeHubDev                    | <6> 2020-09-07 16:55:39.871 +02:00 [INF] - Started AMQP head
edgeHubDev                    | <6> 2020-09-07 16:55:39.874 +02:00 [INF] - Starting HTTP head
edgeHubDev                    | <6> 2020-09-07 16:55:39.997 +02:00 [INF] - User profile is available. Using '"C:\\Users\\ContainerUser\\AppData\\Local\\ASP.NET\\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
edgeHubDev                    | <6> 2020-09-07 16:55:40.029 +02:00 [INF] - Creating key {cf88fc96-5fd3-4c7d-bad0-441bf9f4027e} with creation date 2020-09-07 14:55:40Z, activation date 2020-09-07 14:55:40Z, and expiration date 2020-12-06 14:55:40Z.
edgeHubDev                    | <6> 2020-09-07 16:55:40.074 +02:00 [INF] - Writing data to file '"C:\\Users\\ContainerUser\\AppData\\Local\\ASP.NET\\DataProtection-Keys\\key-cf88fc96-5fd3-4c7d-bad0-441bf9f4027e.xml"'.
edgeHubDev                    | <4> 2020-09-07 16:55:40.450 +02:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
edgeHubDev                    | <6> 2020-09-07 16:55:40.473 +02:00 [INF] - Started HTTP head
edgeHubDev                    | <6> 2020-09-07 16:55:44.346 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:55:44.729 +02:00 [INF] - New token received on the Cbs link
edgeHubDev                    | <6> 2020-09-07 16:55:44.925 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/SimulatedTemperatureSensor with cached service identity vs2019gerlitm/SimulatedTemperatureSensor. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:55:51.897 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:56:03.182 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:56:12.490 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:56:24.489 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:56:35.282 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <6> 2020-09-07 16:56:44.917 +02:00 [INF] - Closing link Events for vs2019gerlitm/SimulatedTemperatureSensor
edgeHubDev                    | <6> 2020-09-07 16:56:46.143 +02:00 [INF] - New token received on the Cbs link
edgeHubDev                    | <6> 2020-09-07 16:56:46.144 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/SimulatedTemperatureSensor with cached service identity vs2019gerlitm/SimulatedTemperatureSensor. Resyncing service identity...
edgeHubDev                    | <4> 2020-09-07 16:56:47.284 +02:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
edgeHubDev                    | <6> 2020-09-07 16:56:49.122 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm/IotEdgeModule1. Resyncing service identity...
edgeHubDev                    | <4> 2020-09-07 16:56:51.724 +02:00 [WRN] - Error while refreshing the service identity for vs2019gerlitm/IotEdgeModule1
edgeHubDev                    | System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
edgeHubDev                    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
edgeHubDev                    |    --- End of inner exception stack trace ---
edgeHubDev                    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\DeviceScopeApiClient.cs:line 121
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\DeviceScopeApiClient.cs:line 99
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\ServiceProxy.cs:line 79
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\DeviceScopeIdentitiesCache.cs:line 72
edgeHubDev                    | <6> 2020-09-07 16:56:51.736 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with module credentials. Attempting to authenticate using device vs2019gerlitm credentials.
edgeHubDev                    | <6> 2020-09-07 16:56:51.736 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/IotEdgeModule1 with cached service identity vs2019gerlitm. Resyncing service identity...
edgeHubDev                    | <4> 2020-09-07 16:56:53.033 +02:00 [WRN] - Error while refreshing the service identity for vs2019gerlitm/SimulatedTemperatureSensor
edgeHubDev                    | System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
edgeHubDev                    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
edgeHubDev                    |    --- End of inner exception stack trace ---
edgeHubDev                    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\DeviceScopeApiClient.cs:line 121
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\DeviceScopeApiClient.cs:line 99
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\ServiceProxy.cs:line 79
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\DeviceScopeIdentitiesCache.cs:line 72
edgeHubDev                    | <6> 2020-09-07 16:56:53.034 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/SimulatedTemperatureSensor with module credentials. Attempting to authenticate using device vs2019gerlitm credentials.
edgeHubDev                    | <6> 2020-09-07 16:56:53.034 +02:00 [INF] - Unable to authenticate client vs2019gerlitm/SimulatedTemperatureSensor with cached service identity vs2019gerlitm. Resyncing service identity...
edgeHubDev                    | <4> 2020-09-07 16:57:00.487 +02:00 [WRN] - Error while refreshing the service identity for vs2019gerlitm/IotEdgeModule1
edgeHubDev                    | System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
edgeHubDev                    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
edgeHubDev                    |    --- End of inner exception stack trace ---
edgeHubDev                    |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
edgeHubDev                    |    at System.Threading.Tasks.ValueTask`1.get_Result()
edgeHubDev                    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
edgeHubDev                    |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\DeviceScopeApiClient.cs:line 121
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\DeviceScopeApiClient.cs:line 99
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.CloudProxy\ServiceProxy.cs:line 79
edgeHubDev                    |    at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in C:\agent\_work\4\s\edge-hub\src\Microsoft.Azure.Devices.Edge.Hub.Core\DeviceScopeIdentitiesCache.cs:line 72
```

**Comment by SLdragon** [comment]
Hi, @gerlitm101 , you can first check whether there is a time drift between the VM and your local system, if the time is wrong, you follow the link below to sync your time:

https://github.com/Azure/iotedgehubdev/issues/266#issuecomment-595233648

**Comment by gerlitm101** [comment]
Hi @SLdragon, thanks for reply. I already disabled and enabled the time synchronization via powershell and restarted my docker engine. Unfortunatly still the same problem that the sas token is generated for two hours earlier than my time is :(

**Comment by SLdragon** [comment]
You can view the logs to see whether the time in the container is correct. If it isn't correct, you need to sync it and restart the vm.
If you are using the physical machine, you should make sure the local system time is correct

**Comment by gerlitm101** [comment]
Found out that my issue is due too corporate network proxy. Anyway, thanks a lot for your support :). I will close the ticket.
