### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by maroonmoon13** [Azure/iotedgehubdev#304]
Installation of iotedgehubdev no longer works on Ubuntu 16.04. pip fails with followiing error:
```
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography import utils, x509
Traceback (most recent call last):
File "/usr/bin/pip", line 9, in
from pip import main
File "/usr/lib/python2.7/dist-packages/pip/init.py", line 13, in
from pip.exceptions import InstallationError, CommandError, PipError
File "/usr/lib/python2.7/dist-packages/pip/exceptions.py", line 6, in
from pip._vendor.six import iteritems
File "/usr/lib/python2.7/dist-packages/pip/_vendor/init.py", line 64, in
vendored("cachecontrol")
File "/usr/lib/python2.7/dist-packages/pip/_vendor/init.py", line 36, in vendored
import(modulename, globals(), locals(), level=0)
File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/init.py", line 9, in
File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in
File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 3, in
File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/init.py", line 53, in
File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 54, in
File "/usr/local/lib/python2.7/dist-packages/OpenSSL/init.py", line 8, in
from OpenSSL import crypto, SSL
File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 14, in
from cryptography import utils, x509
File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/init.py", line 8, in
from cryptography.x509.base import (
File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 23, in
from cryptography.x509.extensions import Extension, ExtensionType
File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 22, in
from cryptography.hazmat.primitives import constant_time, serialization
File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/serialization/init.py", line 22, in
from cryptography.hazmat.primitives.serialization.ssh import (
File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 27, in
from bcrypt import kdf as _bcrypt_kdf
File "/usr/local/lib/python2.7/dist-packages/bcrypt/init.py", line 57
def gensalt(rounds: int = 12, prefix: bytes = b"2b") -> bytes:
^
SyntaxError: invalid syntax
```

**Comment by smcd253** [comment]
Hi @maroonmoon13, thanks for opening this issue. You mentioned in the issue on Azure/iotedgedev that you were experiencing this issue with pip3 as well, correct? If so, can you please try running the following sequence?
```
pip install --upgrade pip
pip install --upgrade --no-cache-dir iotedgehubdev
```

**Comment by maroonmoon13** [comment]
Hi,
This is hat I get when I try to upgarde pip
![image](https://user-images.githubusercontent.com/31255968/106656559-75a5d480-6560-11eb-97ca-4039a1066783.png)

**Comment by smcd253** [comment]
It seems like you're having issues with pip itself. I would recommend running the following and see if you're still having the same issues:
```
sudo apt-get remove python-pip
sudo apt-get autoremove
sudo apt-get install python-pip
pip install --upgrade pip
pip install --upgrade --no-cache-dir iotedgehubdev
```
I would also recommend changing to python 3 if you can. While this tool still supports python 2, more and more packages are beginning to sunset support and you will find it increasingly difficult to maintain python 2 code bases with external dependencies.

**Comment by maroonmoon13** [comment]
The above made no difference. Let me try pip3

**Comment by maroonmoon13** [comment]
On vanilla Ubuntu Server 16.04.7 install, 
sudo apt install python3-pip
sudo pip3 install --upgrade pip==20.3.4
sudo pip3 install --upgrade iotedgedehubdev

thats what will work.

**Comment by maroonmoon13** [comment]
So, the installation went fine. I was also able to set it up and start a single module debug on my machine. But when I try to send a message using curl to debug my module, I get a "curl: (56) Recv failure: Connection reset by peer"
If I send the same curl message again, the error changes to "curl: (52) Empty reply from server"
Are there any logs which I can review/collect for you to see what the problem is?

**Comment by avagraw** [comment]
@maroonmoon13 can you please share how are you sending the curl request.
What tool are you using?
Also, what is the exact curl command you are running?

**Comment by maroonmoon13** [comment]
This is the command I am sending from the device shell:

`curl --location --request POST 'http://localhost:53000/api/v1/messages' --header 'MessageID: 123' --header 'MessageType: Request' --header 'Content-Type: application/json' --data-raw '{"inputName": "DataIn","data":"{\"data\": {\"command\": \"QueryWellListUserCommand\"}}"}'`

**Comment by maroonmoon13** [comment]
the device is a Ubuntu 16.04.7 server VM, which I connect to using ssh. I am also using VS code remote extension to develop. The module is developed and run on the server

**Comment by maroonmoon13** [comment]
Any other information I can provide to resolve this?

**Comment by avagraw** [comment]
@maroonmoon13 it seems you may not be using the correct syntax, can you please try the following CURL command:

curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data":"hello world"}

This is a basic curl command to test if simple test messages are flowing through

**Comment by maroonmoon13** [comment]
I am using a different syntax because my module is a custom module. And from the error message, it doesn't look like a syntax problem.

In your suggestion, there is no location. I will try with that option and see if it makes any difference

**Comment by avagraw** [comment]
@maroonmoon13 were you able to try it out?

**Comment by maroonmoon13** [comment]
Yes. This is what I get.
`curl --request POST --header 'MessageID: 123' --header 'MessageType: Request' --header 'Content-Type: application/json' --data-raw '{"inputName": "DataIn","data":"{\"data\": {\"command\": \"QueryWellListOperationUserCommand\"}}"}'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information`

**Comment by marianan** [comment]
Hi @maroonmoon13 , thanks for reporting this issue. At this point, we don't have a clear indication what is causing the curl errors you are observing. It would be helpful if you can try a vanilla single module and follow the instructions in the readme for this repo. If the issue disappears in this setup then we need to start adding more layers to see what triggers the issue first. Let us know how the vanilla single module communication works.

**Comment by konichi3** [comment]
Closing the issue as there is no update. Feel free to re-open or create a new issue.

**Comment by maroonmoon13** [comment]
Hello,
I would like to reopen the issue as it is not resolved. I tried with a vanilla single module on a ubuntu virtualbox VM and faced the same issue.
Regards

**Comment by konichi3** [comment]
Reopening the issue. This issue is now in our backlog. We will respond when we have an update

**Comment by mhshami01** [comment]
Hello @maroonmoon13, in one of your earlier messages you state that you are using VS code remote extension...

We expect the simulator is to be running locally, also curl requests should be sent on the same machine where the simulator is running.

Please provide the following information:
- Machine and OS where VS Code is running.
- Machine and OS where the simulator is running, if different from VS Code.
- Machine and OS where the module that you are developing/debugging is deployed, if different from that of VS Code.
- The output of the following command on all machines involved:
  docker ps -a
  docker images -a
  iotedgehubdev --version

**Comment by marianan** [comment]
No activity in the last 7 days so closing the issue. Please let us know if the symptoms persist.
