### ISSUE TITLE
Cannot debug on MacOS

### ISSUE THREAD

**Issue by stewartadam** [Azure/iotedgehubdev#308]
Original discussion was in #30 and closed.

Local module debugging on MacOS produces an exception immediately upon launch:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Access is denied.)
 ---> System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Microsoft.Azure.Devices.Client.Edge.InstalledCertificateValidator.SetupCertificateValidation()
   at Microsoft.Azure.Devices.Client.Edge.InstalledCertificateValidator.Create(IList`1 certs)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.GetCertificateValidator(IList`1 certs)
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at SampleModule.Program.Init() in /Users/account/EdgeSolution/modules/SampleModule/Program.cs:line 49
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SampleModule.Program.Main(String[] args) in /Users/account/EdgeSolution/modules/SampleModule/Program.cs:line 20
```

Appears to be related to CA certificate setup. Unclear why one should remove the environment setting for MacOS, and if that cert needs to be trusted in the user's keychain that should be done by the tooling as a part of setup.

**Comment by stewartadam** [comment]
Even after following the proposed workaround in #30 of trusting the certificate in Keychain Access and commenting out the environment variable in VS Code, debugging continues to fail with the exception
```
System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

**Comment by marianan** [comment]
@stewartadam thanks for reporting this issue. The issue is now added to our backlog for investigation. We will update this thread when available.
