### ISSUE TITLE
Re: NVIDIA driver for iotedgehubdev

### ISSUE THREAD

**Issue by gLuColte** [Azure/iotedgehubdev#363]
Hi I am running into a similar issue to this
```
https://github.com/Azure/iotedgehubdev/issues/205
```
Everything runs perfectly when deployed on to an actual Edge Device. However, when attempting to use
```
iotedgehubdev start -d config/deployment.json
```
To run a simulator locally, following trace back is raised:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 612, in to   
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
On the host machine, I am certain that the nvidia is properly installed:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 471.41       Driver Version: 471.41       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8     8W /  N/A |    161MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

What would be the most likely reason that causes this issue of running custom module not able to link with host GPU?

Similar to the above Issue, the runtime under inspect shows the following:
```
"Runtime": "runc",
```

Which is different to expected 'Nvidia'
```
"Runtime": "nvidia",
```

**Comment by marianan** [comment]
@garyJune thanks for reporting this issue. This behavior is supported by docker-compose, so we will need a few additional data points.
1. Current deployment.json file and docker-compose.yml (C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml).
2. expected-docker-compose.yml - this is modified docker-compose.yml, allowing your module to access the NVIDIA GPU. 
- Output from 'docker-compose -f expected-docker-compose.yml up'
- Output from 'docker-compose -v'

**Comment by marianan** [comment]
Closing due to inactivity. Feel free to create a new issue if the symptoms persist.
