### ISSUE TITLE
Cannot find executable of Azure IoT Edge simulator

### ISSUE THREAD

**Issue by felixmondelo** [Azure/iotedgehubdev#379]
I have updated Azure IoT Edge Simulator to the 0.14.11 version, but now I can't launch my developments as usual from Visual Studio 2019, I get this error:

```
[1>------ Build started: Project: Cosentino.Edge.Deployment, Configuration: Debug Any CPU ------
1>DOCKER_HOST:
1>DOCKER_TLS_VERIFY:
1>DOCKER_CERT_PATH:
1>Additional Env Variables:
1>SimulatorPath: C:\Users\fmondelo\Documents\Visual Studio 2019\iotedgehubdev\v0.14.11\iotedgehubdev
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): warning : Cannot find executable of Azure IoT Edge simulator, please click menu 'Tools -> Azure IoT Edge Tools -> Update IoT Edge simulator' to reinstall simulator and try again.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : Failed to exec task with error System.Exception: Cannot find executable of Azure IoT Edge simulator, please click menu 'Tools -> Azure IoT Edge Tools -> Update IoT Edge simulator' to reinstall simulator and try again.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at Microsoft.VisualStudio.Azure.IoT.Edge.BuildTasks.PrepareEdgeCliTask.<ExecuteCoreAsync>d__21.MoveNext()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at Microsoft.VisualStudio.Azure.IoT.Edge.BuildTasks.PrepareEdgeCliTask.<ExecuteCoreAsync>d__21.MoveNext()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error : --- End of stack trace from previous location where exception was thrown ---
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Azure IoT Edge Tools\AzureIoTEdgeProject.Build.targets(19,5): error :    at Microsoft.VisualStudio.Azure.IoT.Edge.BuildTasks.EdgeTaskBase.<ExecuteAsync>d__22.MoveNext()
1>Done building project "Cosentino.Edge.Deployment.iotedgeproj" -- FAILED.](url)
```
The executable is installed on the folder, I can execute it from a command line:

![image](https://user-images.githubusercontent.com/14011841/156362556-2dfad62a-ede6-4b3b-a18b-94020e0788b0.png)

What can be the problem?

**Comment by mhshami01** [comment]
Hello @felixmondelo - thank you for reporting this issue. Please uninstall and reinstall the VS IoT Edge Extension and try again.

**Comment by felixmondelo** [comment]
Hi @mhshami01, I tried that several times before open this issue, but it didn't work.

I have resolved the issue updating also Visual Studio 2019.

Now it works, thank you so much.
