### ISSUE TITLE
certificates Problem with cryptography-39.0.0

### ISSUE THREAD

**Issue by onexipStefan** [Azure/iotedgehubdev#406]
Since January we have the problem that Iotedgehubdev uses the dependency cryptography-39.0.0 when installing in the Docker environment.
This probably causes a problem with the certificates used in our development environment. Until 23/12/2022, the Iotedgehubdev installation in the Docker environment still worked (used cryptography-38.0.4).

Log output snippet:
--------------------
[pool-4-thread-1] INFO iotedgehubdev - Traceback (most recent call last):
[pool-4-thread-1] INFO iotedgehubdev -   File "/home/vsts/.local/bin/iotedgehubdev", line 5, in <module>
[pool-4-thread-1] INFO iotedgehubdev -     from iotedgehubdev.cli import main
[pool-4-thread-1] INFO iotedgehubdev -   File "/home/vsts/.local/lib/python3.8/site-packages/iotedgehubdev/cli.py", line 15, in <module>
[pool-4-thread-1] INFO iotedgehubdev -     from .edgecert import EdgeCert
[pool-4-thread-1] INFO iotedgehubdev -   File "/home/vsts/.local/lib/python3.8/site-packages/iotedgehubdev/edgecert.py", line 4, in <module>
[pool-4-thread-1] INFO iotedgehubdev -     from .certutils import EdgeCertUtil
[pool-4-thread-1] INFO iotedgehubdev -   File "/home/vsts/.local/lib/python3.8/site-packages/iotedgehubdev/certutils.py", line 6, in <module>
[pool-4-thread-1] INFO iotedgehubdev -     from OpenSSL import crypto
[pool-4-thread-1] INFO iotedgehubdev -   File "/home/vsts/.local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
[pool-4-thread-1] INFO iotedgehubdev -     from OpenSSL import crypto, SSL
[pool-4-thread-1] INFO iotedgehubdev -   File "/home/vsts/.local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3268, in <module>
[pool-4-thread-1] INFO iotedgehubdev -     _lib.OpenSSL_add_all_algorithms()
[pool-4-thread-1] INFO iotedgehubdev - AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
-----------------------

Any ideas what is going wrong ?

**Comment by kalajdzija** [comment]
+1

I solved that issue (on MacOS) by upgrading the PyOpenSSL to 23.0.0 over pip (python 3.9) by running:

`pip3.9 install --upgrade pip
pip3.9 install --upgrade pyOpenSSL`

**Comment by konichi3** [comment]
Closing due to inactivity.
