### ISSUE TITLE
Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized

### ISSUE THREAD

**Issue by czgtest** [Azure/iotedgehubdev#95]
step:
1. iotedgehubdev setup -c "HostName=czghub.azure-devices.net;DeviceId=edge1015;SharedAccessKey=fb/Cf4ays3CUZS0B/1I1/eHH7D10UsnimC7IaNYpgFU="

2.iotedgehubdev start -d deployment.json

3. see edgeHubDev logs

```
C:\Users\v-czg>docker logs edgeHubDev
[2018-10-15 03:54:14 : Starting Edge Hub
[10/15/2018 03:54:14.663 AM] Edge Hub Main()
2018-10-15 03:54:18.475 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-10-15 03:54:18.521 +00:00 [INF] - Created device scope identities cache
2018-10-15 03:54:18.525 +00:00 [INF] - Starting refresh of device scope identities cache
2018-10-15 03:54:18.529 +00:00 [INF] - Starting Edge Hub
2018-10-15 03:54:18.530 +00:00 [INF] - Version - 1.0.3.17521421 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)
2018-10-15 03:54:18.531 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-10-15 03:54:18.531 +00:00 [INF] - Installing intermediate certificates.
2018-10-15 03:54:18.621 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-10-15 03:54:18.621 +00:00 [INF] - Created new message store
2018-10-15 03:54:18.793 +00:00 [INF] - Initializing configuration
2018-10-15 03:54:19.832 +00:00 [INF] - Set the following 2 route(s) in edge hub
2018-10-15 03:54:19.834 +00:00 [INF] - r1: FROM /messages/modules/SampleModule/outputs/* INTO $upstream
2018-10-15 03:54:19.834 +00:00 [INF] - r2: FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO BrokeredEndpoint("/modules/SampleModule/inputs/input1")
2018-10-15 03:54:19.835 +00:00 [INF] - Updated message store TTL to -1 seconds
2018-10-15 03:54:19.836 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-10-15 03:54:19.836 +00:00 [INF] - Initialized edge hub configuration
2018-10-15 03:54:19.856 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2018-10-15 03:54:20.454 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2018-10-15 03:54:20.473 +00:00 [INF] - Starting MQTT head
2018-10-15 03:54:20.503 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
2018-10-15 03:54:20.648 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-10-15 03:54:20.732 +00:00 [INF] - Starting AMQP head
2018-10-15 03:54:20.755 +00:00 [INF] - Started MQTT head
2018-10-15 03:54:20.854 +00:00 [INF] - Started AMQP head
2018-10-15 03:54:20.857 +00:00 [INF] - Starting HTTP head
2018-10-15 03:54:20.985 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-10-15 03:54:21.020 +00:00 [INF] - Creating key {4830c683-49d8-43e3-89c9-2c0c597196ea} with creation date 2018-10-15 03:54:21Z, activation date 2018-10-15 03:54:20Z, and expiration date 2019-01-13 03:54:20Z.
2018-10-15 03:54:21.037 +00:00 [WRN] - No XML encryptor configured. Key {4830c683-49d8-43e3-89c9-2c0c597196ea} may be persisted to storage in unencrypted form.
2018-10-15 03:54:21.043 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-4830c683-49d8-43e3-89c9-2c0c597196ea.xml"'.
2018-10-15 03:54:21.771 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-10-15 03:54:21.859 +00:00 [INF] - Started HTTP head
2018-10-15 03:54:22.247 +00:00 [INF] - New token received on the Cbs link
2018-10-15 03:54:22.343 +00:00 [INF] - New token received on the Cbs link
2018-10-15 03:54:24.107 +00:00 [WRN] - Error while refreshing the service identity for edge1015/SampleModule
Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiException: Message: Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized, Content: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:d00a90ecec3b460e88a8067e8026e4d6-G:7-TimeStamp:10/15/2018 03:54:24"}
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 115
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 85
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs:line 77
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 140
2018-10-15 03:54:24.176 +00:00 [INF] - Attempting to connect to IoT Hub for client edge1015/SampleModule via AMQP...
2018-10-15 03:54:24.208 +00:00 [INF] - Created cloud proxy for client edge1015/SampleModule via AMQP, with client operation timeout 20000.
2018-10-15 03:54:24.218 +00:00 [INF] - Initialized cloud proxy d892e0f1-0ad2-49bc-a91b-413e299522ef for edge1015/SampleModule
2018-10-15 03:54:24.219 +00:00 [INF] - Created cloud connection for client edge1015/SampleModule
2018-10-15 03:54:24.226 +00:00 [INF] - New cloud connection created for device edge1015/SampleModule
2018-10-15 03:54:24.717 +00:00 [WRN] - Error while refreshing the service identity for edge1015/tempSensor
Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiException: Message: Error getting device scope result from IoTHub, HttpStatusCode: Unauthorized, Content: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:8d08ff1144d6450680295a10d760244f-G:9-TimeStamp:10/15/2018 03:54:24"}
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScope(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 115
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.DeviceScopeApiClient.GetIdentitiesInScopeWithRetry(Uri uri) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceScopeApiClient.cs:line 85
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.ServiceProxy.GetServiceIdentity(String deviceId, String moduleId) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs:line 77
   at Microsoft.Azure.Devices.Edge.Hub.Core.DeviceScopeIdentitiesCache.RefreshServiceIdentity(String id) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs:line 140
2018-10-15 03:54:24.719 +00:00 [INF] - Attempting to connect to IoT Hub for client edge1015/tempSensor via AMQP...
2018-10-15 03:54:24.719 +00:00 [INF] - Created cloud proxy for client edge1015/tempSensor via AMQP, with client operation timeout 20000.
2018-10-15 03:54:24.719 +00:00 [INF] - Initialized cloud proxy ebe0f80c-1691-4653-a7f3-ca24b735db3b for edge1015/tempSensor
2018-10-15 03:54:24.719 +00:00 [INF] - Created cloud connection for client edge1015/tempSensor
2018-10-15 03:54:24.719 +00:00 [INF] - New cloud connection created for device edge1015/tempSensor
2018-10-15 03:54:25.903 +00:00 [INF] - New token requested by client edge1015/SampleModule, but using existing token as it is usable.
2018-10-15 03:54:25.935 +00:00 [INF] - New token requested by client edge1015/tempSensor, but using existing token as it is usable.
2018-10-15 03:54:27.207 +00:00 [INF] - Exiting disconnected state
2018-10-15 03:54:27.209 +00:00 [INF] - Cloud connection for edge1015/SampleModule is True
2018-10-15 03:54:27.217 +00:00 [INF] - Connection status for edge1015/SampleModule changed to ConnectionEstablished
2018-10-15 03:54:27.224 +00:00 [INF] - Processing subscriptions for client edge1015/SampleModule.
2018-10-15 03:54:27.247 +00:00 [INF] - Cloud connection for edge1015/tempSensor is True
2018-10-15 03:54:27.247 +00:00 [INF] - Connection status for edge1015/tempSensor changed to ConnectionEstablished
2018-10-15 03:54:27.247 +00:00 [INF] - Processing subscriptions for client edge1015/tempSensor.
2018-10-15 03:54:27.249 +00:00 [INF] - Entering connected state
2018-10-15 03:54:27.256 +00:00 [INF] - Authenticated edge1015/SampleModule with IotHub
2018-10-15 03:54:27.262 +00:00 [INF] - Token updated for edge1015/SampleModule
2018-10-15 03:54:27.361 +00:00 [INF] - Authenticated edge1015/tempSensor with IotHub
2018-10-15 03:54:27.361 +00:00 [INF] - Token updated for edge1015/tempSensor
2018-10-15 03:54:27.467 +00:00 [INF] - New device connection for device edge1015/SampleModule
2018-10-15 03:54:27.469 +00:00 [INF] - Bind device proxy for device edge1015/SampleModule
2018-10-15 03:54:27.471 +00:00 [INF] - Initialized AMQP connection handler for edge1015/SampleModule
2018-10-15 03:54:27.496 +00:00 [INF] - Opened link Events for edge1015/SampleModule
2018-10-15 03:54:27.507 +00:00 [INF] - New device connection for device edge1015/tempSensor
2018-10-15 03:54:27.508 +00:00 [INF] - Bind device proxy for device edge1015/tempSensor
2018-10-15 03:54:27.508 +00:00 [INF] - Initialized AMQP connection handler for edge1015/tempSensor
2018-10-15 03:54:27.508 +00:00 [INF] - Opened link Events for edge1015/tempSensor
2018-10-15 03:54:27.642 +00:00 [INF] - Processing subscription ModuleMessages for client edge1015/SampleModule.
2018-10-15 03:54:27.643 +00:00 [INF] - Opened link ModuleMessages for edge1015/SampleModule
2018-10-15 03:54:27.657 +00:00 [INF] - Opened link MethodReceiving for edge1015/tempSensor
2018-10-15 03:54:27.661 +00:00 [INF] - Processing subscription Methods for client edge1015/tempSensor.
2018-10-15 03:54:28.318 +00:00 [INF] - Opened link MethodSending for edge1015/tempSensor
2018-10-15 03:54:28.365 +00:00 [INF] - Processing subscription ModuleMessages for client edge1015/tempSensor.
2018-10-15 03:54:28.366 +00:00 [INF] - Opened link ModuleMessages for edge1015/tempSensor
```

**Comment by LazarusX** [comment]
Fixed in https://github.com/Azure/iotedgehubdev/pull/96/files
